### ISSUE TITLE
Installing on MacOS 10.15.4 - dependency problems

### ISSUE THREAD

**Issue by jaredvacanti** [darconeous/CCIDU2F#1]
I'm unfortunately having trouble installing CCIDU2F onto a laptop running MacOS Catalina 10.15.4 (19E287). The installation instructions mention to first install https://github.com/github/SoftU2F. I get this message installing v0.0.19:

<img width="734" alt="Screen Shot 2020-04-10 at 4 13 56 PM" src="https://user-images.githubusercontent.com/2007559/79028774-05543f80-7b57-11ea-8713-94cce4679807.png">

Perhaps this is related to https://github.com/github/SoftU2F/issues/75. I did see this message once, but have not been able to reproduce it.

Initially when I ran CCIDU2F from Xcode I got a `kext` error - now it runs successfully but with no debugging output. (It was mentioned elsewhere that there should be a lot of logging, so I'm suspicious). The installation guide mentions installing SoftU2F and then using `launchctl unload ...` to adjust the process. Is there an alternative? Is there a way to install the kext required directly?

Does this work on lower OS versions? Is a downgrade required?

**Comment by darconeous** [comment]
It should only log messages when a smart card is inserted or removed. It prints nothing initially. If you saw that error from SoftU2F#75, then the kext is installed. Connect a reader and insert a card, see what happens.

**Comment by darconeous** [comment]
The ‘launchctl unload’ just stops the SoftU2F app, which allows the CCIDU2F process to connect to the kext. The kext only supports one process at a time, so we have to stop the SoftU2F one in order for CCIDU2F to be able to make the fake HID device upon card insertion.

**Comment by jaredvacanti** [comment]
When I insert the card into a contact reader I get this error:

```
2020-04-11 21:07:14.611365-0500 CCIDU2F[891:8826] Smart card added to "FEITIAN iR301": <TKSmartCardATR: 0x10043cbb0 3b 18-ff T=1:--- T=1:fe-- T=15:c3--;7(c82113) 6(050363510002)>
2020-04-11 21:07:14.619266-0500 CCIDU2F[891:8826] U2F check
2020-04-11 21:07:14.646486-0500 CCIDU2F[891:8826] Card supports U2F!
2020-04-11 21:07:14.647062-0500 CCIDU2F[891:8826] Enabling Fake U2F HID Device
SoftU2F.kext not loaded.
(lldb) 
```

So I believe the kext installation did fail. I'll try to install it without the pkg.

**Comment by darconeous** [comment]
If I remember correctly, I had to install the package twice to get it to work. The first time failed, the second time worked. I can't remember the details.

The reason we need their kext and don't try building it ourselves is because that would require turning off system integrity protection. By using Github's signed kext we can avoid the need for that.

**Comment by jaredvacanti** [comment]
Referencing this issue https://github.com/github/SoftU2F/issues/64 was able to help me to install SoftU2F. I had to allow GitHub signed packages to be installed in `System Preferences > Security & Privacy> General` otherwise the installation fails silently.

Running

```
grep SoftU2F -a20 -b20 /var/log/install.log | sort -g | uniq | tail -n200
```

is helpful to track down more about that error for anyone else experiencing trouble.

After that, https://github.com/darconeous/u2f-javacard runs fine on Mac OS!
